// Generated by CoffeeScript 1.8.0
(function() {
  var Patient;

  Patient = (function() {
    function Patient(name, code) {
      this.name = name;
      this.code = code;
    }

    return Patient;

  })();

}).call(this);

//# sourceMappingURL=first-sort.js.map
