// Generated by CoffeeScript 1.8.0
(function() {
  var Patient, Queue, ed, p, seen;

  Queue = require('../queue');

  Patient = (function() {
    function Patient(name, code) {
      this.name = name;
      this.code = code;
    }

    return Patient;

  })();

  ed = new Queue();

  p = new Patient("Smith", 5);

  ed.enqueue(p);

  p = new Patient("Jones", 4);

  ed.enqueue(p);

  p = new Patient("Fehrenbach", 6);

  ed.enqueue(p);

  p = new Patient("Brown", 1);

  ed.enqueue(p);

  p = new Patient("Ingram", 1);

  ed.enqueue(p);

  console.log(ed.toString2());

  seen = ed.firstDequeue();

  console.log("Patient being treated: " + seen[0].name);

  console.log("Patients waiting to be seen: ");

  console.log(ed.toString2());

  seen = ed.firstDequeue();

  console.log("Patient being treated: " + seen[0].name);

  console.log("Patients waiting to be seen: ");

  console.log(ed.toString2());

  seen = ed.firstDequeue();

  console.log("Patient being treated: " + seen[0].name);

  console.log("Patients waiting to be seen: ");

  console.log(ed.toString2());

}).call(this);

//# sourceMappingURL=first-sort.js.map
