// Generated by CoffeeScript 1.8.0
(function() {
  var BST, inOrder, nums;

  BST = require('../Node');

  nums = new BST();

  nums.insert(23);

  nums.insert(45);

  nums.insert(16);

  nums.insert(37);

  nums.insert(3);

  nums.insert(99);

  nums.insert(22);

  console.log(nums);

  console.log(nums.root.show());

  console.log("Inorder traversal: ");

  inOrder = function(node) {
    if (node !== null) {
      inOrder(node.left);
      console.log(node.show());
      return inOrder(node.right);
    }
  };

  inOrder(nums.root);

}).call(this);

//# sourceMappingURL=method.js.map
