// Generated by CoffeeScript 1.8.0
(function() {
  var Stack, isPalindrome, word, word2;

  Stack = require('../stack');

  isPalindrome = function(word) {
    var i, rword, s, _i, _len;
    s = new Stack();
    for (_i = 0, _len = word.length; _i < _len; _i++) {
      i = word[_i];
      s.push(i);
    }
    rword = '';
    while (s.length()) {
      rword += s.pop();
    }
    if (word !== rword) {
      return false;
    }
    return true;
  };

  word = "hello";

  word2 = "racecar";

  console.log("" + word, isPalindrome(word));

  console.log("" + word2, isPalindrome(word2));

}).call(this);

//# sourceMappingURL=isPalindrome.js.map
