// Generated by CoffeeScript 1.8.0
(function() {
  var Stack, mulBase, newNum;

  Stack = require('../stack');

  mulBase = function(num, base) {
    var converted, s;
    s = new Stack();
    while (true) {
      s.push(num % base);
      num = Math.floor(num /= base);
      if (num <= 0) {
        break;
      }
    }
    converted = "";
    while (s.length() > 0) {
      converted += s.pop();
    }
    return converted;
  };

  newNum = mulBase(125, 8);

  console.log(newNum);

}).call(this);

//# sourceMappingURL=mulBase.js.map
