// Generated by CoffeeScript 1.8.0
(function() {
  var Dictionary, pbook;

  Dictionary = require('../Dictionary');

  pbook = new Dictionary();

  pbook.add("Mike", "123");

  pbook.add("David", "345");

  pbook.add("Cynthia", "456");

  console.log("David's extension: " + pbook.find("David"));

  console.log("Number of entries: " + pbook.count());

  pbook.remove("David");

  pbook.showAll();

  pbook.clear();

  console.log("Number of entries: " + pbook.count());

}).call(this);

//# sourceMappingURL=method.js.map
