// Generated by CoffeeScript 1.8.0
(function() {
  var Stack, s;

  Stack = (function() {
    function Stack() {
      this.dataStore = [];
      this.top = 0;
    }

    Stack.prototype.push = function(element) {
      return this.dataStore[this.top++] = element;
    };

    Stack.prototype.pop = function() {
      return this.dataStore[--this.top];
    };

    Stack.prototype.peek = function() {
      return this.dataStore[this.top - 1];
    };

    Stack.prototype.length = function() {
      return this.top;
    };

    Stack.prototype.clear = function() {
      return this.top = 0;
    };

    return Stack;

  })();

  s = new Stack();

  s.push("David");

  s.push("Raymond");

  s.push("Bryan");

  console.log("s =>", s);

  console.log("s.length()", s.length());

  console.log("s.peek()", s.peek());

  console.log("s.pop()", s.pop());

  console.log("s ==>", s);

}).call(this);

//# sourceMappingURL=stack.js.map
