// Generated by CoffeeScript 1.8.0
(function() {
  var HashTable, hTable, i, someNames, _i, _len;

  HashTable = require('../HashTable');

  someNames = ["David", "Jennifer", "Donnie", "Raymond", "Cynthia", "Mike", "Clayton", "Danny", "Jonathan"];

  hTable = new HashTable();

  for (_i = 0, _len = someNames.length; _i < _len; _i++) {
    i = someNames[_i];
    hTable.put(i);
  }

  hTable.showDistro();

}).call(this);

//# sourceMappingURL=method.js.map
