// Generated by CoffeeScript 1.10.0
(function() {
  var Stack, baseConverter;

  Stack = require('../stack');

  baseConverter = function(decNumber, base) {
    var baseString, digits, rem, remStack;
    remStack = new Stack();
    rem = '';
    baseString = '';
    digits = '0123456789ABCDEF';
    while (decNumber > 0) {
      rem = Math.floor(decNumber % base);
      remStack.push(rem);
      decNumber = Math.floor(decNumber / base);
    }
    while (remStack.isEmpty() === false) {
      baseString += digits[remStack.pop()];
    }
    return baseString;
  };

  console.log(baseConverter(100345, 2));

  console.log(baseConverter(100345, 8));

  console.log(baseConverter(100345, 16));

}).call(this);

//# sourceMappingURL=baseConverter.js.map
