// Generated by CoffeeScript 1.10.0
(function() {
  var Stack, divideBy2;

  Stack = require('../stack');

  divideBy2 = function(decNumber) {
    var binaryString, rem, remStack;
    remStack = new Stack();
    binaryString = '';
    rem = '';
    while (decNumber > 0) {
      rem = Math.floor(decNumber % 2);
      remStack.push(rem);
      decNumber = Math.floor(decNumber / 2);
    }
    while (remStack.isEmpty() === false) {
      binaryString += remStack.pop().toString();
    }
    return binaryString;
  };

  console.log(divideBy2(233));

  console.log(divideBy2(10));

  console.log(divideBy2(1000));

}).call(this);

//# sourceMappingURL=divideBy2.js.map
