// Generated by CoffeeScript 1.10.0
(function() {
  var Stack, stack;

  Stack = require('../stack');

  stack = new Stack();

  console.log(stack.isEmpty());

  stack.push(5);

  stack.push(8);

  console.log(stack.peek());

  stack.push(11);

  console.log(stack.size());

  console.log(stack.isEmpty());

  stack.push(15);

  stack.pop();

  stack.pop();

  console.log(stack.size());

  stack.print();

}).call(this);

//# sourceMappingURL=test-methond.js.map
