// Generated by CoffeeScript 1.8.0
(function() {
  var CArray, myNums, numElements;

  CArray = (function() {
    function CArray(numElements) {
      var i;
      this.numElements = numElements;
      this.dataStore = [];
      this.pos = 0;
      i = 0;
      while (i < this.numElements) {
        this.dataStore[i] = i;
        i++;
      }
    }

    CArray.prototype.insert = function(element) {
      return this.dataStore[this.pos++] = element;
    };

    CArray.prototype.toString = function() {
      var i, k, restr, _i, _len, _ref;
      restr = '';
      _ref = this.dataStore;
      for (k = _i = 0, _len = _ref.length; _i < _len; k = ++_i) {
        i = _ref[k];
        restr += i + " ";
        if (k > 0 & k % 10 === 0) {
          restr += '\n';
        }
      }
      return restr;
    };

    CArray.prototype.clear = function() {
      var i, _i, _len, _ref, _results;
      _ref = this.dataStore;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push(i = 0);
      }
      return _results;
    };

    CArray.prototype.setData = function() {
      var i;
      i = 0;
      while (i < this.numElements) {
        this.dataStore[i] = Math.floor(Math.random() * (this.numElements + 1));
        i++;
      }
    };

    CArray.prototype.swap = function(arr, index1, index2) {
      var temp;
      temp = arr[index1];
      arr[index1] = arr[index2];
      arr[index2] = temp;
    };

    CArray.prototype.bubbleSort = function() {
      var inner, numElements, outer, _results;
      numElements = this.dataStore.length;
      outer = numElements;
      _results = [];
      while (outer >= 2) {
        inner = 0;
        while (inner <= outer - 1) {
          if (this.dataStore[inner] > this.dataStore[inner + 1]) {
            this.swap(this.dataStore, inner, inner + 1);
          }
          inner++;
        }
        _results.push(outer--);
      }
      return _results;
    };

    return CArray;

  })();

  numElements = 4;

  myNums = new CArray(numElements);

  myNums.setData();

  myNums.bubbleSort();

  console.log(myNums.toString());

}).call(this);

//# sourceMappingURL=CArray.js.map
