// Generated by CoffeeScript 1.8.0
(function() {
  var Dictionary;

  Dictionary = (function() {
    function Dictionary() {
      this.datastore = new Array();
      this.add = function(key, val) {
        this.datastore[key] = val;
      };
      this.find = function(key) {
        return this.datastore[key];
      };
      this.remove = function(key) {
        delete this.datastore[key];
      };
      this.showAll = function() {
        var k, v, _ref, _results;
        _ref = this.datastore;
        _results = [];
        for (k in _ref) {
          v = _ref[k];
          _results.push(console.log(k + " -> " + v));
        }
        return _results;
      };
      this.count = function() {
        var k, n;
        n = 0;
        for (k in this.datastore) {
          n++;
        }
        return n;
      };
      this.clear = function() {
        var k, v, _ref, _results;
        _ref = this.datastore;
        _results = [];
        for (v in _ref) {
          k = _ref[v];
          _results.push(delete this.datastore[v]);
        }
        return _results;
      };
    }

    return Dictionary;

  })();

  module.exports = Dictionary;

}).call(this);

//# sourceMappingURL=Dictionary.js.map
